
export const SET_LOADING = "SET_LOADING";

export const SET_VERIFICATION_CODE = "SET_VERIFICATION_CODE";
export const SET_EMAIL_FOR_RESET_PASSWORD = "SET_EMAIL_FOR_RESET_PASSWORD";

export const LOGIN_ATTEMPT = "LOGIN_ATTEMPT";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const VALIDATE_TOKEN_ATTEMPT = "VALIDATE_TOKEN_ATTEMPT";
export const VALIDATE_TOKEN_FAILED = "VALIDATE_TOKEN_FAILED";
export const VALIDATE_TOKEN_SUCCESS = "VALIDATE_TOKEN_SUCCESS";

export const LOGOUT_ATTEMPT = "LOGOUT_ATTEMPT";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_ATTEMPT = "REGISTER_ATTEMPT";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";


export const UPDATE_USER_ATTEMPT = "UPDATE_USER_ATTEMPT";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const COMPLETE_PROFILE_ATTEMPT = "COMPLETE_PROFILE_ATTEMPT";
export const COMPLETE_PROFILE_FAILED = "COMPLETE_PROFILE_FAILED";
export const COMPLETE_PROFILE_SUCCESS = "COMPLETE_PROFILE_SUCCESS";

export const SEND_VERIFICATION_CODE = "SEND_VERIFICATION_CODE";
export const RESEND_VERIFICATION_CODE = "RESEND_VERIFICATION_CODE";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const VERIFY_EMAIL_ATTEMPT = "VERIFY_EMAIL_ATTEMPT";
export const VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";

export const GET_EXPLORE_DATA_ATTEMPT = "GET_EXPLORE_DATA_ATTEMPT";
export const GET_EXPLORE_DATA_FAILED = "GET_EXPLORE_DATA_FAILED";
export const GET_EXPLORE_DATA_SUCCESS = "GET_EXPLORE_DATA_SUCCESS";

export const CHECK_ABLE_TO_CHAT_ATTEMPT = "CHECK_ABLE_TO_CHAT_ATTEMPT"
export const CHECK_ABLE_TO_CHAT_FAILED = "CHECK_ABLE_TO_CHAT_FAILED"
export const CHECK_ABLE_TO_CHAT_SUCCESS = "CHECK_ABLE_TO_CHAT_SUCCESS"
